[#106] Fix using ./ in paths
serokell/xrefcheck pull request #109
Opened 2022-07-07 13:37 UTC by s-and-witch

## Description

We used strings equality on file path, but we can have different strings for the same path, for example `./` and `././`, so I added path normalisation at code where we compare them.

Happily, in 9.6 will be new opaque FilePath type, so nobody will use (==) from strings on them.

## Related issue(s)

- Fixed #106

2022-07-08 15:09 UTC, dcastro requested changes

2022-07-08 15:09 UTC, dcastro commented on src/Xrefcheck/Scan.hs
> -    rootNE = if null root then "." else root
Nice catch! :+1:

2022-07-08 15:09 UTC, dcastro commented on src/Xrefcheck/CLI.hs
> +filepathOption = fmap normalise <$> strOption
We should probably do this in _all_ places where we read filepaths from an external source / use hardcoded filepaths.

As far as I can tell, we're only missing 2 places: `readConfig` and `defConfig`. We should probably have a `normaliseFilePaths :: Config -> Config` function, and use it inside `readConfig` / `defConfig`.

2022-07-08 15:20 UTC, Player-205 commented on src/Xrefcheck/Scan.hs
> +  | fp == "." = ""
BTW, we use locationOf in one place, on the root variable, that already normalised. I think, better to move this function into where block.

2022-07-08 15:22 UTC, dcastro commented on src/Xrefcheck/Scan.hs
> +  | fp == "." = ""
Sure, sounds good

2022-07-08 15:26 UTC, dcastro commented on tests/golden/check-localhost.bats
> +@test "Config: missing, reduchant slashes" {
Probably a bats file+folder for each individual option

2022-07-13 07:59 UTC, dcastro requested changes

2022-07-13 07:59 UTC, dcastro commented on .buildkite/pipeline.yml
> +    label: Golden tests for CLI options (bats)
Oh, we should just have one CI step for running all bats tests.

2022-07-13 07:59 UTC, dcastro commented on .buildkite/pipeline.yml
> +    label: Golden tests for CLI options (bats)
You can do `cd tests/golden && bats ./**` to run all bats tests in all subdirs.

On the other hand, this does mean that the "working directory" for all tests will be `tests/golden`, so they'll probably start failing. You can do what we did in coffer:

* Create a helper file with a setup function that changes the working dir ([example](https://github.com/serokell/coffer/blob/main/tests/golden/helpers.bash))
* Add `load '../helpers` at the top of every bats file ([example](https://github.com/serokell/coffer/blob/main/tests/golden/delete-field-command/delete-field-command.bats))

2022-07-14 10:35 UTC, dcastro approved these changes

2022-07-14 10:36 UTC, merged