Sereja313/#76 add tests for virtual files glob patterns
serokell/xrefcheck pull request #136
Opened 2022-09-09 11:12 UTC by Sereja313

## Description

Problem: The `virtualFiles` config allows the user to use glob patterns
to specify files that do not physically exist in the repository but
should be treated as existing nevertheless. However, we do not yet
have any around our usage of glob patterns. We should write some to
1) ensure it behaves in a sensible way even in corner cases and 2)
document  the behaviour.

Solution: Add tests that document how the `virtualFiles` glob paterns work.

## Related issue(s)

Fixes #76 

## :white_check_mark: Checklist for your Pull Request

Ideally a PR has all of the checkmarks set.

If something in this list is irrelevant to your PR, you should still set this
checkmark indicating that you are sure it is dealt with (be that by irrelevance).

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [ ] I checked whether I should update the docs and did so if necessary:
    - [README](/README.md)
    - Haddock

- Public contracts
  - [ ] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [ ] I added an entry to the [changelog](/CHANGES.md) if my changes are visible to the users
        and
  - [ ] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [ ] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [ ] My code complies with the [style guide](/docs/code-style.md).

2022-09-16 14:29 UTC, Sorokin-Anton approved these changes
Maybe I would add some negative tests too (to check that no extra files are ignored)

2022-09-16 16:13 UTC, dcastro requested changes
LGTM :+1: 

I would also _enhance_ this test (no need to create a new test) to make sure virtual files are always relative to the root directory (and not the file being checked).

I.e., a file in `one/file.md` should be able to link to simply `./a.md` and also to `../two/b.md`

2022-09-17 07:02 UTC, dcastro approved these changes

2022-09-18 21:01 UTC, Sorokin-Anton approved these changes

2022-09-19 07:35 UTC, merged