[#254] Revise dump-config command
serokell/xrefcheck pull request #257
Opened 2022-12-22 12:25 UTC by aeqz

## Description

Problem: xrefcheck does not allow to print the config to stdout instead of writing it to a file. Also, it is easy to overwrite you changes by mistake by executing the command again.

Solution: provide a --stdout flag to print the config to stdout, and do not write it to a file unless a --force flag has been included.

## Related issue(s)

Fixes #

## :white_check_mark: Checklist for your Pull Request

Ideally a PR has all of the checkmarks set.

If something in this list is irrelevant to your PR, you should still set this
checkmark indicating that you are sure it is dealt with (be that by irrelevance).

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [ ] I checked whether I should update the docs and did so if necessary:
    - [README](https://github.com/serokell/xrefcheck/tree/master/README.md)
    - Haddock

- Public contracts
  - [ ] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [ ] I added an entry to the [changelog](https://github.com/serokell/xrefcheck/tree/master/CHANGES.md) if my changes are visible to the users
        and
  - [ ] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [ ] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [ ] My code complies with the [style guide](https://github.com/serokell/style/blob/master/haskell.md).

2022-12-22 12:25 UTC, Martoon-00 commented on tests/golden/check-dump-config/.config.yaml
> +# SPDX-License-Identifier: MPL-2.0
I have found a missing newline at the end of this file:
```suggestion:-0+0
# SPDX-License-Identifier: MPL-2.0

```



<p align="right" data-meta="generated_by_instant-checks">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

2022-12-22 12:25 UTC, Martoon-00 commented on tests/golden/check-dump-config/.xrefcheck.yaml
> +# SPDX-License-Identifier: MPL-2.0
I have found a missing newline at the end of this file:
```suggestion:-0+0
# SPDX-License-Identifier: MPL-2.0

```



<p align="right" data-meta="generated_by_instant-checks">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

2022-12-22 12:25 UTC, Martoon-00 commented
<!--
  1 Error: Trailing whitespaces and/or in...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Trailing whitespaces and/or incorrect end-of-file newlines detected.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_instant-checks">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2022-12-22 18:21 UTC, Martoon-00 requested changes
Nice :+1: 

Still leaving a few suggestions.

2022-12-22 20:37 UTC, aeqz commented on exec/Main.hs
> +    DumpConfig repoType (DCMFile f path) -> do
Exactly! It was because of the name collision. `forceFlag` sounds good.

2022-12-22 20:38 UTC, aeqz commented on package.yaml
> +      - directory
Don't worry. I will sort `dependencies` and `default-extensions` in a separate commit.

2022-12-23 00:22 UTC, Martoon-00 approved these changes
Awesome, thank you.

There is a typo in the 8edffa205033eae77539b218cb97edea9a4ed4c0 commit's subject, but other than that looks good.

2022-12-23 14:13 UTC, Martoon-00 commented
<!--
  1 Error: WIP commits are still there.
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">WIP commits are still there.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_premerge-checks">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2022-12-29 11:12 UTC, Martoon-00 commented
This PR is quite small, I think let's merge it.

2022-12-29 12:04 UTC, merged